before_script:
  - git config user.email "d.retnan@nhubnigeria.com"
  - git config user.name "GitLab CI on behalf of Logical Address Inc."

push_to_heroku:
  script:
    - git commit --allow-empty -m "Publish to Heroku at $(date)"
    - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/launcher-api.git master