apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushdeploy-api
  namespace: default
  labels:
    app: pushdeploy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushdeploy-api
  template:
    metadata:
      labels:
        app: pushdeploy-api
    spec:
      containers:
        - name: pushdeploy-api
          image: logicaladdress/pushdeploy-api:$COMMIT_SHA1
          ports:
            - containerPort: 80
              name: http
