apiVersion: v1
kind: Service
metadata:
  name: pushdeploy-api
  namespace: default
  labels:
    app: pushdeploy-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: pushdeploy-api