version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: node:8.11.4
      - image: mongo:4.2.1
      - image: redis:5.0.3
    environment:
      MONGODB_URL: mongodb://localhost:27017/pushdeploy
      REDIS_URL: redis://localhost:6379
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm -g install grunt-cli jasmine
            - run: grunt test
  build-publish-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: logicaladdress/pushdeploy-api
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: ./bin/ci-deploy.sh
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - build-publish-image:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test