version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: node:8.11.4
      - image: mongo:4.2.1
      - image: redis:5.0.3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm -g install grunt-cli jasmine
            - run: grunt test
workflows:
    build-and-test:
      jobs:
        - build-and-test
