apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushdeploy-api
  namespace: default
  labels:
    app: pushdeploy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushdeploy-api
  template:
    metadata:
      labels:
        app: pushdeploy-api
    spec:
      containers:
        - name: pushdeploy-api
          image: logicaladdress/pushdeploy-api:$COMMIT_SHA1
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: API_URL
              value: $API_URL
            - name: GIT_WEB_HOOK_URL
              value: $GIT_WEB_HOOK_URL
            - name: BITBUCKET_PUBLIC_KEY
              value: $BITBUCKET_PUBLIC_KEY
            - name: BITBUCKET_SECRET_KEY
              value: $BITBUCKET_SECRET_KEY
            - name: GITHUB_PUBLIC_KEY
              value: $GITHUB_PUBLIC_KEY
            - name: GITHUB_SECRET_KEY
              value: $GITHUB_SECRET_KEY
            - name: MONGODB_URL
              value: $MONGODB_URL
            - name: REDIS_URL
              value: $REDIS_URL
            - name: STRIPE_PLAN_A
              value: plan_HDfzkKEuGMYgs3
            - name: STRIPE_PLAN_B
              value: plan_HDg0oNkzkvikaq
            - name: STRIPE_PUBLIC_KEY
              value: $STRIPE_PUBLIC_KEY
            - name: STRIPE_SECRET_KEY
              value: $STRIPE_SECRET_KEY
            - name: RECAPTCHA_SECRET
              value: $RECAPTCHA_SECRET
