apiVersion: v1
kind: Service
metadata:
  name: pushdeploy-api
  namespace: default
  labels:
    app: pushdeploy-api
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "17099136-747f-41fc-9583-7ab665e350bc"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    app: pushdeploy-api