kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicdpushdeploy
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cicdpushdeploy
    namespace: default
roleRef:
  kind: Role
  name: cicdpushdeploy
  apiGroup: rbac.authorization.k8s.io
